import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/css/styles.css'
import Header from '../components/Header';
import { APP_NAME, GOOGLE_ANALYTICS_ID, PRODUCTION } from '@/config';
import { GoogleAnalytics } from '@next/third-parties/google';

export const metadata = {
  title: APP_NAME,
  description: 'Generated by create next app',
}

const setGoogleAnalytics = () => {
  if (PRODUCTION) {
    return <GoogleAnalytics gaId={GOOGLE_ANALYTICS_ID}/>
  }
}

export default function RootLayout({ children }) {
  return (
    <React.Fragment>
    <html lang="en">
      <body className="d-flex flex-column min-vh-100">
        <Header />
        {children}
        <footer className="mt-auto" style={{marginBottom : 30}}>
          <div className="container">
            <span className="text-muted" style={{display: 'flex', justifyContent: 'center'}}> 
              Place sticky footer content here.
            </span>
          </div>
        </footer>
      </body>
      {setGoogleAnalytics()}
    </html>
    </React.Fragment>
  )
}
