import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/css/styles.css'
import Header from '../components/Header';
import { APP_NAME } from '@/config';

export const metadata = {
  title: APP_NAME,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <React.Fragment>
    <html lang="en">
      <body className="d-flex flex-column min-vh-100">
        <Header />
        {children}
        <footer className="mt-auto" style={{marginBottom : 30}}>
          <div className="container">
            <span className="text-muted" style={{display: 'flex', justifyContent: 'center'}}> 
              Place sticky footer content here.
            </span>
          </div>
        </footer>
      </body>
    </html>
    </React.Fragment>
  )
}
