import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from '../components/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <React.Fragment>
    <html lang="en">
      <body>
        <Header />
        {children}
        <p>footer</p>
      </body>
    </html>
    </React.Fragment>
  )
}
